# 에러 처리

## 에러 처리의 필요성

- 에러는 언제나 발생할 수 있고, 에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 발생한 에러에 대해 대처하지 않고, 방치하면 프로그램은 강제 종료된다.

```jsx
console.log("[Start]");

foo(); // ReferenceError: foo is not defined
// 발생한 에러를 방치하면 프로그램은 강제 종료된다.

// 에러에 의해 프로그램이 강제 종료되어 아래 코드는 실행되지 않는다.
console.log("[End]");
```

- try/catch문을 사용하여 발생한 에러에 대응하면 프로그램이 강제 종료되지 않고, 코드를 실행시킬 수 있다.

```jsx
console.log("[Start]");

try {
  foo();
} catch (error) {
  console.error("[에러 발생]", error);
  // [에러 발생] ReferenceError: foo is not defined
}

// 발생한 에러에 적절한 대응을 하면 프로그램이 강제 종료되지 않는다.
console.log("[End]");
```

- 에러가 발생하지 않는 예외적인 상황이 발생할 수 있다. 또한, 예외적인 상황에 적절하게 대응하지 않으면 에러로 이어질 수 있다.

```jsx
// DOM에 button 요소가 존재하지 않으면 querySelector 메서드는 에러를 발생시키지 않고 null을 반환한다.
const $button = document.querySelector("button"); // null

$button.classList.add("disabled");
// TypeError: Cannot read property 'classList' of null
```

- querySelector메서드는 인수로 전달한 문자열이 css선택자 문법에 맞지 않는 경우 에러를 발생시킨다.

```jsx
// DOM에 button 요소가 존재하는 경우 querySelector 메서드는 에러를 발생시키지 않고 null을 반환한다.
const $button = document.querySelector("button"); // null
$button?.classList.add("disabled");
```

- 옵셔널 체이닝 연산자 .?를 사용하여 에러를 방지하였다.

<br>

## try catch finally문

에러 처리를 구현하는 방법은 크게 2가지로 나뉜다.

1. if문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인해서 처리하는 방법과
2. 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법 try/catch/finally

```jsx
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

```jsx
console.log("[Start]");

try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
  foo();
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
  console.error(err); // ReferenceError: foo is not defined
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
  console.log("finally");
}

// try...catch...finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.
console.log("[End]");
```

<br>

## Error 객체

Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.

```jsx
const error = new Error("invalid");
```

- Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다.
- message 프로퍼티의 값은 Error 생성자 함수에 인수로 전달한 에러 메시지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열이고, 디버깅 목적으로 사용함.

7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수)

```jsx
1 @ 1;    // SyntaxError: Invalid or unexpected token
foo();    // ReferenceError: foo is not defined
null.foo; // TypeError: Cannot read property 'foo' of null
new Array(-1); // RangeError: Invalid array length
decodeURIComponent('%'); // URIError: URI malformed
```

<br>

## throw 문

- Error 생성자 함수로 에러 객체를 생성하면 에러가 발생하는 것은 아님. 에러 객체 생성과 에러 발생은 다른 것이다.

```jsx
try {
  // 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
  new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

- 에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객체를 던져야함.

```jsx
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

- throw문에서 에러를 던지면 catch문의 에러 변수가 생성되고, 던져진 에러 객체가 할당된다.

<br>

# 참고

- 모던 자바스크립트 딥 다이브
